### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thaisaurard** [Clm-Roig/javaGraph#2]
We can't even count the issues
With all our love <3

**Comment by Clm-Roig** [comment]
Fastest fix ever
See you soon motherfucker :heart:

**Comment by thaisaurard** [comment]
GG

**Comment by Clm-Roig** [comment]
Shut up is closed.

**Comment by thaisaurard** [comment]
I'm a motherfucking unicorn ~*o*~    ^3^   °\^0^/°
